// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxgQ7iR_kULaDPTG3S53TDn5u0LeoEnpE',
    appId: '1:950953298249:web:a2195faae27fe3a57c3298',
    messagingSenderId: '950953298249',
    projectId: 'metro-connect-pi',
    authDomain: 'metro-connect-pi.firebaseapp.com',
    storageBucket: 'metro-connect-pi.firebasestorage.app',
    measurementId: 'G-RPWBL50TD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWNaqFSXYvKB_mw6wQJQpILvmsiWr1pks',
    appId: '1:950953298249:android:d6a4dd5b7864118c7c3298',
    messagingSenderId: '950953298249',
    projectId: 'metro-connect-pi',
    storageBucket: 'metro-connect-pi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABK86D4F9xrCVmOzYcbbgWA1jJkaPUBFM',
    appId: '1:950953298249:ios:47d7c113ab1f1cc07c3298',
    messagingSenderId: '950953298249',
    projectId: 'metro-connect-pi',
    storageBucket: 'metro-connect-pi.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

}